modified:   builders/build.yaml 	modified:   builders/deploy.yaml 	modified:   scripts/build 	modified:   scripts/deploy

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -18,9 +18,15 @@ set -eEuo pipefail
 
 ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"
 ALL_SERVICES="cleanup-export,cleanup-exposure,export,exposure,federationin,federationout"
+REGION_GCR="${REGION:0:2}"
 
 if [ -z "${PROJECT_ID:-}" ]; then
   echo "✋ Missing PROJECT_ID!" >&2
+  exit 1
+fi
+
+if [ -z "${REGION:-}" ]; then
+  echo "✋ Missing REGION!" >&2
   exit 1
 fi
 
